version: '3'

services:
  ## PHP-FPM ##############################################
  laravel:
    build:
      context: ./
    environment:
      - PUID=${DOCKER_PUID}
      - PGID=${DOCKER_PGID}
    volumes:
      - ./:/srv/api
    extra_hosts:
        -   "host.docker.internal:host-gateway"
    depends_on:
      - pgsql
    networks:
      - code-network


  ### MAILHOG Server #########################################
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - "8025:8025"
    networks:
        - code-network
  ### NGINX Server #########################################
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/srv/api
      - ./admin/dist:/srv/api/admin
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "443:443"
    restart: always
    depends_on:
      - laravel
    networks:
        - code-network

##########################################################
  certbot:
    image: certbot/certbot:latest
    volumes:
        - ./certbot/www:/var/www/certbot/:rw

##########################################################
  pgsql:
    image: "postgres" # use latest official postgres version
    ports:
        - 5432:5432
    environment:
        POSTGRES_USER: "${DB_USERNAME}"
        POSTGRES_PASSWORD: "${DB_PASSWORD}"
        POSTGRES_DB: "${DB_DATABASE}"
    volumes:
        - pgsql-admin-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    networks:
        - code-network

############################################################
  pgadmin:
      image: dpage/pgadmin4
      restart: always
      environment:
          PGADMIN_DEFAULT_EMAIL: "${PGADMIN_EMAIL}"
          PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASSWORD}"
      ports:
          - "5050:80"
      networks:
          - code-network

############################################################
volumes:
    pgsql-admin-data: # named volumes can be managed easier using docker-compose

networks:
    code-network:
        driver: bridge
